version: "3.9"

services:
  remind-bot-wppconnect:
    image: registry.local:5000/remind-bot-wppconnect:latest
    networks:
      - remind-bot-network
    volumes:
      - remind-bot-wppconnect-data:/usr/src/wpp-server/tokens

  remind-bot:
    image: registry.local:5000/remind-bot:latest
    networks:
      - remind-bot-network

networks:
  remind-bot-network:
    driver: overlay

volumes:
  remind-bot-wppconnect-data:
