services:
  remind-bot:
    container_name: remind-bot
    build: .
    restart: unless-stopped
    networks:
      - evolution-network
    environment:
      EVOLUTION_API_URL: http://evolution-api:3333
    env_file:
      - .env

networks:
  evolution-network:
    external: true
    name: evolution_evolution-network